### ISSUE TITLE
Beetle PSX HW not available on Kodi Omega

### ISSUE THREAD

**Issue by f-lawe** [kodi-game/game.libretro.beetle-psx-hw#1]
### Describe the bug
Here is a clear and concise description of what the problem is:

I wanted to add some PS1 games to my Kodi install, and I noticed that only Beetle PSX was available on Omega, not the HW version. Is there any reason? It it possible to help solve this?

## RetroArch Behavior
Here is a clear and concise description of what happens in RetroArch with the same core/game:

HW looks to be a bit more efficient (at least, my PS1 roms are clearly not loaded properly with the software rendered one).

### To Reproduce

NA

### Debuglog

The debuglog can be found here:
NA

### Screenshots 
Here are some links or screenshots to help explain the problem:

NA

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

Operating system version/name: Windows 11 64 bits

Kodi version: Omega 21.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
The reason the HW core isn't available is because it requires OpenGL, and currently Kodi doesn't support OpenGL cores. A lot of work has gone into this, but it needs someone to bring it over the finish line. You can find the tracking issue here: https://github.com/xbmc/xbmc/issues/17743

**Comment by f-lawe** [comment]
Oh, ok. Thanks for the quick reply, I now understand. That’s unfortunately far beyond my reach, gonna stay focused on Orange TV and Orange Radio. 

I’m closing the issue has there is not much to add.

**Comment by garbear** [comment]
Just reporting in, we're close to merging the first half of the code for GL support: https://github.com/xbmc/xbmc/pull/26091. Still a long ways away, but we're making it there.
